# This file is generated by rules_erlang via the erlang_config macro

load(
    "%{RULES_ERLANG_WORKSPACE}//private:erlang_build.bzl",
    "erlang_build",
)
load(
    "%{RULES_ERLANG_WORKSPACE}//tools:erlang_toolchain.bzl",
    "erlang_toolchain",
)

erlang_build(
    name = "otp-%{ERLANG_NAME}",
    version = "%{ERLANG_VERSION}",
    url = "%{URL}",
    strip_prefix = "%{STRIP_PREFIX}",
    sha256v = "%{SHA_256}",
    pre_configure_cmds = %{PRE_CONFIGURE_CMDS},
    extra_configure_opts = %{EXTRA_CONFIGURE_OPTS},
    post_configure_cmds = %{POST_CONFIGURE_CMDS},
    extra_make_opts = %{EXTRA_MAKE_OPTS},
)

erlang_toolchain(
    name = "erlang_%{ERLANG_MAJOR}_%{ERLANG_MINOR}_toolchain",
    otp = ":otp-%{ERLANG_NAME}",
    visibility = ["//visibility:public"],
)

toolchain(
    name = "toolchain_major",
    exec_compatible_with = [
        "//:erlang_internal",
    ],
    target_compatible_with = [
        "//:erlang_%{ERLANG_MAJOR}",
    ],
    toolchain = ":erlang_%{ERLANG_MAJOR}_%{ERLANG_MINOR}_toolchain",
    toolchain_type = "%{RULES_ERLANG_WORKSPACE}//tools:toolchain_type",
    visibility = ["//visibility:public"],
)

alias(
    name = "toolchain",
    actual = "toolchain_major",
    visibility = ["//visibility:public"],
)

toolchain(
    name = "toolchain_major_minor",
    exec_compatible_with = [
        "//:erlang_internal",
    ],
    target_compatible_with = [
        "//:erlang_%{ERLANG_MAJOR}_%{ERLANG_MINOR}",
    ],
    toolchain = ":erlang_%{ERLANG_MAJOR}_%{ERLANG_MINOR}_toolchain",
    toolchain_type = "%{RULES_ERLANG_WORKSPACE}//tools:toolchain_type",
    visibility = ["//visibility:public"],
)

alias(
    name = "toolchain2",
    actual = "toolchain_major_minor",
    visibility = ["//visibility:public"],
)
